- name: install docker engine - community for ubuntu
  hosts: all
  tasks:
    - name: uninstall old versions
      apt:
        name: ["docker", "docker-engine", "docker.io", "containerd", "runc"]
        state: absent
      become: true

    - name: install dependencies
      apt:
        name:
          [
            "apt-transport-https",
            "ca-certificates",
            "curl",
            "gnupg-agent",
            "software-properties-common",
          ]
        update_cache: yes

    - name: add docker’s official gpg key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: create docker_repo_cmd
      command: bash -c "echo \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\" "
      register: docker_repo_cmd

    - debug: msg="{{ docker_repo_cmd.stdout }}"

    - name: add docker apt repository
      apt_repository:
        repo: "{{ docker_repo_cmd.stdout }}"

    - name: install docker engine - community
      apt:
        name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        update_cache: yes
